"""HTML report generator for firmware analysis results."""

import html
import json
from datetime import datetime, timezone
from pathlib import Path

from ..core.context import AnalysisContext


def generate_html_report(context: AnalysisContext) -> str:
    """Generate a standalone HTML report from analysis results."""
    arch_str = ""
    if context.arch_info:
        arch_str = f"{context.arch_info.cpu_family.value} {context.arch_info.endianness.value}-endian {context.arch_info.word_size}bit"

    components_html = _render_components_table(context)
    warnings_html = _render_warnings(context)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Firmware Analysis Report - {html.escape(context.firmware_path.name)}</title>
<style>
* {{ margin: 0; padding: 0; box-sizing: border-box; }}
body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #f5f7fa; color: #2d3748; line-height: 1.6; padding: 2rem; }}
.container {{ max-width: 1200px; margin: 0 auto; }}
.header {{ background: linear-gradient(135deg, #1a365d 0%, #2b6cb0 100%); color: white; padding: 2rem; border-radius: 12px; margin-bottom: 2rem; }}
.header h1 {{ font-size: 1.8rem; margin-bottom: 0.5rem; }}
.header .subtitle {{ opacity: 0.9; font-size: 0.95rem; }}
.card {{ background: white; border-radius: 8px; padding: 1.5rem; margin-bottom: 1.5rem; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }}
.card h2 {{ font-size: 1.2rem; color: #1a365d; margin-bottom: 1rem; border-bottom: 2px solid #e2e8f0; padding-bottom: 0.5rem; }}
.info-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 1rem; }}
.info-item {{ padding: 0.75rem; background: #f7fafc; border-radius: 6px; border-left: 3px solid #3182ce; }}
.info-item .label {{ font-size: 0.8rem; color: #718096; text-transform: uppercase; letter-spacing: 0.05em; }}
.info-item .value {{ font-size: 1rem; font-weight: 600; color: #2d3748; margin-top: 0.25rem; word-break: break-all; }}
table {{ width: 100%; border-collapse: collapse; }}
th {{ background: #edf2f7; color: #4a5568; font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.05em; padding: 0.75rem 1rem; text-align: left; }}
td {{ padding: 0.75rem 1rem; border-bottom: 1px solid #e2e8f0; font-size: 0.9rem; }}
tr:hover {{ background: #f7fafc; }}
.badge {{ display: inline-block; padding: 0.2rem 0.6rem; border-radius: 12px; font-size: 0.75rem; font-weight: 600; }}
.badge-os {{ background: #bee3f8; color: #2a4365; }}
.badge-lib {{ background: #c6f6d5; color: #22543d; }}
.badge-fw {{ background: #fed7d7; color: #742a2a; }}
.confidence-bar {{ width: 60px; height: 8px; background: #e2e8f0; border-radius: 4px; display: inline-block; vertical-align: middle; }}
.confidence-fill {{ height: 100%; border-radius: 4px; background: #48bb78; }}
.confidence-fill.medium {{ background: #ecc94b; }}
.confidence-fill.low {{ background: #fc8181; }}
.methods {{ font-size: 0.75rem; color: #718096; }}
.warning {{ padding: 0.5rem 1rem; background: #fffbeb; border-left: 3px solid #f6ad55; margin-bottom: 0.5rem; border-radius: 4px; font-size: 0.85rem; }}
.footer {{ text-align: center; color: #a0aec0; font-size: 0.8rem; margin-top: 2rem; }}
.stats {{ display: flex; gap: 2rem; margin-bottom: 1rem; }}
.stat {{ text-align: center; }}
.stat .number {{ font-size: 2rem; font-weight: 700; color: #3182ce; }}
.stat .label {{ font-size: 0.8rem; color: #718096; }}
</style>
</head>
<body>
<div class="container">
    <div class="header">
        <h1>Firmware Analysis Report</h1>
        <div class="subtitle">Generated by firmware-scanner v0.2.0 | {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}</div>
    </div>

    <div class="card">
        <h2>Firmware Information</h2>
        <div class="info-grid">
            <div class="info-item">
                <div class="label">File Name</div>
                <div class="value">{html.escape(context.firmware_path.name)}</div>
            </div>
            <div class="info-item">
                <div class="label">File Size</div>
                <div class="value">{len(context.raw_data):,} bytes</div>
            </div>
            <div class="info-item">
                <div class="label">SHA-256</div>
                <div class="value">{context.file_hash_sha256}</div>
            </div>
            <div class="info-item">
                <div class="label">Architecture</div>
                <div class="value">{html.escape(arch_str) or 'Unknown'}</div>
            </div>
            <div class="info-item">
                <div class="label">Detected RTOS</div>
                <div class="value">{html.escape(context.detected_rtos) or 'Unknown'} ({context.rtos_confidence:.0%})</div>
            </div>
            <div class="info-item">
                <div class="label">Format</div>
                <div class="value">{html.escape(context.metadata.get('format', 'Unknown'))}</div>
            </div>
        </div>
    </div>

    <div class="card">
        <h2>Component Summary</h2>
        <div class="stats">
            <div class="stat">
                <div class="number">{len(context.components)}</div>
                <div class="label">Total Components</div>
            </div>
            <div class="stat">
                <div class="number">{sum(1 for c in context.components if c.resolved_version and 'unknown' not in c.resolved_version)}</div>
                <div class="label">With Version</div>
            </div>
            <div class="stat">
                <div class="number">{sum(1 for c in context.components if c.component_type == 'operating-system')}</div>
                <div class="label">RTOS/OS</div>
            </div>
            <div class="stat">
                <div class="number">{sum(1 for c in context.components if c.component_type == 'library')}</div>
                <div class="label">Libraries</div>
            </div>
        </div>
    </div>

    <div class="card">
        <h2>Detected Components ({len(context.components)})</h2>
        {components_html}
    </div>

    {warnings_html}

    <div class="footer">
        <p>firmware-scanner v0.2.0 | CycloneDX SBOM available via CLI</p>
    </div>
</div>
</body>
</html>"""


def _render_components_table(context: AnalysisContext) -> str:
    if not context.components:
        return "<p>No components detected.</p>"

    rows = ""
    for comp in sorted(context.components, key=lambda c: c.name.lower()):
        badge_class = "badge-os" if comp.component_type == "operating-system" else \
                      "badge-fw" if comp.component_type == "firmware" else "badge-lib"
        type_label = comp.component_type.replace("-", " ").title()

        max_conf = max((v.confidence for v in comp.versions), default=0)
        conf_class = "" if max_conf >= 0.7 else "medium" if max_conf >= 0.4 else "low"
        conf_width = int(max_conf * 100)

        methods = ", ".join(sorted(set(v.method.value for v in comp.versions)))

        version_display = html.escape(comp.resolved_version or "unknown")

        rows += f"""<tr>
            <td><strong>{html.escape(comp.name)}</strong></td>
            <td>{version_display}</td>
            <td>{html.escape(comp.vendor)}</td>
            <td><span class="badge {badge_class}">{type_label}</span></td>
            <td>
                <div class="confidence-bar"><div class="confidence-fill {conf_class}" style="width:{conf_width}%"></div></div>
                {max_conf:.0%}
            </td>
            <td class="methods">{html.escape(methods)}</td>
        </tr>"""

    return f"""<table>
        <thead><tr>
            <th>Component</th>
            <th>Version</th>
            <th>Vendor</th>
            <th>Type</th>
            <th>Confidence</th>
            <th>Methods</th>
        </tr></thead>
        <tbody>{rows}</tbody>
    </table>"""


def _render_warnings(context: AnalysisContext) -> str:
    if not context.warnings and not context.errors:
        return ""

    items = ""
    for w in context.warnings:
        items += f'<div class="warning">{html.escape(w)}</div>'
    for e in context.errors:
        items += f'<div class="warning">Error in {html.escape(e.stage)}: {html.escape(e.message)}</div>'

    return f"""<div class="card">
        <h2>Warnings & Errors</h2>
        {items}
    </div>"""
